[book]
authors = ["saai-sudarsanan-swym"]
language = "en"
multilingual = false
src = "src"
title = "sample-doc"

[output.html]
additional-css=["custom.css"]

[output.html.fold]
enable = true
level = 0